### ISSUE TITLE
Error in $.shinyoutput

### ISSUE THREAD

**Issue by Jacqvb** [jessekps/dexter#2]
Hello, The Netherlands here, I was looking for a new way to do IRT analysis and DexterGUI seemed like a good place to start! However I’ve run into some problems:
I use:
R version 3.6.2 (2019-12-12) 
RStudio Version 1.2.5033
(both updated to newest versions after I suspected that the error was due to older versions)

After loading the packages this happens: --> I first open a new project, then select a file for the scoring rules (excel), following I get: 

Warning: Error in $.shinyoutput: Reading from shinyoutput object is not allowed.
  [No stack trace available]

Could you please inform me if I’m doing anything wrong or if this is a bug indeed? If you need more info please let me know.
Thanks in advance!

**Comment by jessekps** [comment]
Hi,

It's a horrible error message certainly so that should be corrected. Not sure if it's a bug per sé. Could you include some lines from your scoring rules file to help me make sense of the problem?

**Comment by Jacqvb** [comment]
Hi,

Thank you for the quick response!
These are the first 10 lines, including column names:

item_id | nOptions | key
-- | -- | --
CRa_1 | 5 | E
CRa_2 | 5 | B
CRa_3 | 5 | D
CRa_4 | 5 | D
CRa_5 | 5 | A
CRa_6 | 5 | B
CRa_7 | 5 | B
CRa_8 | 5 | C
CRa_9 | 5 | C
CRa_10 | 5 | A

**Comment by jessekps** [comment]
I did get an error trying to read your keys, though it wasn't the same as yours. It was a bug that surfaced because of a recent update of dplyr. Anyway, I fixed that and I hope it fixes your problem.

If you could try installing the new version like:

`devtools::install_github('jessekps/dextergui')`

and let me know if the problem is fixed?

**Comment by Jacqvb** [comment]
Hi, thanks! I will try that later (probably this evening, I'm away from my computer today). I'll let you know what happens.Op 13 feb. 2020 08:31 schreef jessekps <notifications@github.com>:I did get an error trying to read your keys, though it wasn't the same as yours. It was a bug that surfaced because of a recent update of dplyr. Anyway, I fixed that and I hope it fixes your problem.
If you could try installing the new version like:
devtools::install_github('jessekps/dextergui')
and let me know if the problem is fixed?

**Comment by Jacqvb** [comment]
I've installed the new version as above and now it works great. Thank you for the quick response and fix!
